In [112]:
import numpy as np
import random

particles = 0
radius = 5 #edge radius
size = 15 #size of the grid
x0 = int((size-1)/2)
tree = np.zeros([size,size]) # n X n array means array center is [(n-1)/2,(n-1)/2] when n is odd
tree[x0,x0] = 1
tree



array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [115]:
#Function to return the random point on the "edge"

def Spawn():
    x = random.randrange(x0 - radius, x0 + radius + 1)
    rand1 = random.randrange(2)
    if rand1 == 0:
        y = np.sqrt(radius*radius - (x - x0)*(x - x0)) + x0
        print("x =", x, "| y =", round(y))
        #coords[0] = x
        #coords[1] = int(y)
    else:
        y = -np.sqrt(radius*radius - (x - x0)*(x - x0)) + x0
        print("x =", x, "| y =", round(y))
        #coords[0] = x
        #coords[1] = int(y)
    return x, round(y)

i=1
while i<1000:
    x = 0
    y = 0
    x, y = Spawn()
#    print(x,y)
    tree[x, y] = 1
    i+=1
#    print(tree)

print(tree)


x = 5 | y = 2
x = 3 | y = 10
x = 10 | y = 3
x = 4 | y = 3
x = 4 | y = 11
x = 3 | y = 4
x = 2 | y = 7
x = 8 | y = 2
x = 3 | y = 4
x = 3 | y = 10
x = 10 | y = 3
x = 3 | y = 10
x = 9 | y = 2
x = 10 | y = 3
x = 3 | y = 4
x = 9 | y = 2
x = 9 | y = 2
x = 2 | y = 7
x = 2 | y = 7
x = 6 | y = 2
x = 8 | y = 12
x = 2 | y = 7
x = 6 | y = 2
x = 7 | y = 12
x = 2 | y = 7
x = 7 | y = 12
x = 9 | y = 2
x = 11 | y = 4
x = 12 | y = 7
x = 9 | y = 2
x = 2 | y = 7
x = 2 | y = 7
x = 5 | y = 2
x = 10 | y = 3
x = 3 | y = 4
x = 12 | y = 7
x = 11 | y = 4
x = 11 | y = 4
x = 4 | y = 11
x = 7 | y = 12
x = 2 | y = 7
x = 6 | y = 12
x = 4 | y = 3
x = 6 | y = 12
x = 12 | y = 7
x = 7 | y = 12
x = 8 | y = 2
x = 2 | y = 7
x = 2 | y = 7
x = 5 | y = 12
x = 2 | y = 7
x = 9 | y = 12
x = 12 | y = 7
x = 5 | y = 2
x = 7 | y = 2
x = 6 | y = 12
x = 7 | y = 12
x = 10 | y = 3
x = 8 | y = 12
x = 11 | y = 4
x = 2 | y = 7
x = 4 | y = 3
x = 10 | y = 11
x = 6 | y = 12
x = 7 | y = 2
x = 8 | y = 12
x = 7 | y = 2
x = 3 | y = 10
x = 3 | y = 4

In [68]:
#Move the particle to the aggregate

print((x - x0)*(x - x0) + (y - x0)*(y - x0))
i=0
while i < 10000:
    if np.sqrt((x - x0)*(x - x0) + (y - x0)*(y - x0)) > 1.2*radius:
        break
    elif tree[x + 1, y] == 1 or tree[x - 1, y] == 1 or tree[x, y + 1] == 1 or tree[x, y - 1] == 1:
        particles += 1
        break
    else:
        print("##############################################################")
        print("##############################################################")
        print("##############################################################")
        print(tree)
        print("##############################################################")
        print("##############################################################")
        print("##############################################################")
        
        rand2 = random.randrange(4)
        if rand2 == 0:
            tree[x, y] = 0
            x+=1
            tree[x, y] = 1
            print("down")
        elif rand2 == 1:
            tree[x, y] = 0
            x-=1
            tree[x, y] = 1
            print("up")
        elif rand2 == 2:
            tree[x, y] = 0
            y+=1
            tree[x, y] = 1
            print("right")
        elif rand2 == 3:
            tree[x, y] = 0
            y-=1
            tree[x, y] = 1
            print("left")
        
        print(tree)
        i+=1

print((x - x0)*(x - x0) + (y - x0)*(y - x0))

25
##############################################################
##############################################################
##############################################################
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
##############################################################
########################